channels:
- conda-forge
dependencies:
- python=3.8.16
- pip<=21.3.1
- pip:
  - mlflow<3,>=2.3
  - cloudpickle==2.2.1
  - pandas==1.1.5
  - psutil==5.8.0
  - scikit-learn==0.24.2
  - typing-extensions==4.5.0
name: mlflow-env
