channels:
- conda-forge
dependencies:
- python=3.8.16
- pip<=21.3.1
- pip:
  - mlflow<3,>=2.3
  - joblib
  - cloudpickle==2.2.1
  - numpy
  - pandas==1.1.5
  - psutil==5.8.0
  - scikit-learn==0.24.2
  - typing-extensions==4.5.0
  - azureml-defaults==1.53.0
  - azureml-inference-server-http
  - azure-ai-ml
  - azure-identity
  - inference-schema
name: mlflow-env
